-- Curated baseline exercise library generated from exercise_library_review_template.csv.
-- Review supabase/exercise_library_review_template.csv first, then run this after schema.sql.
--
-- This intentionally soft-deletes older built-in exercise libraries rather than
-- hard-deleting referenced exercise rows. The app should treat deleted_at as
-- inactive when reading normalized exercise rows.

begin;

update public.exercises
set deleted_at = now(),
    updated_at = now()
where user_id is null
  and is_builtin = true
  and source <> 'curated_exercise_library_v1';

insert into public.exercises (
  user_id,
  name,
  description,
  image_url,
  image_storage_path,
  image_alt,
  equipment,
  primary_muscle,
  secondary_muscles,
  is_builtin,
  source,
  source_key
)
values
  (null, 'Arnold Press', null, null, null, 'Arnold Press', 'Dumbbells', 'Front Delts', array['Side Delts', 'Traps'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:arnold-press-dumbbells'),
  (null, 'Behind-the-Back Curls', null, null, null, 'Behind-the-Back Curls', 'Cable', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:behind-the-back-curls-cable'),
  (null, 'Bench Press', null, null, null, 'Bench Press', 'Barbell', 'Chest', array['Triceps', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bench-press-barbell'),
  (null, 'Bench Press', null, null, null, 'Bench Press', 'Dumbbells', 'Chest', array['Triceps', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bench-press-dumbbells'),
  (null, 'Bench Press with Close Grip', null, null, null, 'Bench Press with Close Grip', 'Barbell', 'Triceps', array['Chest', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bench-press-with-close-grip-barbell'),
  (null, 'Bent-Over Lateral Raises', null, null, null, 'Bent-Over Lateral Raises', 'Dumbbells', 'Rear Delts', array['Traps', 'Side Delts', 'Upper Back', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-lateral-raises-dumbbells'),
  (null, 'Bent-Over One-Arm Rows', null, null, null, 'Bent-Over One-Arm Rows', 'Landmine', 'Upper Back', array['Lats', 'Traps', 'Lower Back', 'Biceps', 'Rear Delts', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-one-arm-rows-barbell'),
  (null, 'Bent-Over Rows', null, null, null, 'Bent-Over Rows', 'Barbell', 'Upper Back', array['Lats', 'Traps', 'Lower Back', 'Biceps', 'Rear Delts', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-rows-barbell'),
  (null, 'Bent-Over Rows', null, null, null, 'Bent-Over Rows', 'Dumbbells', 'Upper Back', array['Lats', 'Traps', 'Lower Back', 'Biceps', 'Rear Delts', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-rows-dumbbells'),
  (null, 'Bent-Over Rows with Reverse Grip', null, null, null, 'Bent-Over Rows with Reverse Grip', 'Barbell', 'Upper Back', array['Lats', 'Traps', 'Lower Back', 'Biceps', 'Rear Delts', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-rows-with-reverse-grip-barbell'),
  (null, 'Bent-Over Rows with Reverse Grip', null, null, null, 'Bent-Over Rows with Reverse Grip', 'Dumbbells', 'Upper Back', array['Lats', 'Traps', 'Lower Back', 'Biceps', 'Rear Delts', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-rows-with-reverse-grip-dumbbells'),
  (null, 'Bent-Over Rows with Wide Grip', null, null, null, 'Bent-Over Rows with Wide Grip', 'Barbell', 'Upper Back', array['Lats', 'Traps', 'Lower Back', 'Biceps', 'Rear Delts', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-rows-with-wide-grip-barbell'),
  (null, 'Bent-Over Shrugs', null, null, null, 'Bent-Over Shrugs', 'Barbell', 'Traps', array['Forearms', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-shrugs-barbell'),
  (null, 'Bent-Over Shrugs', null, null, null, 'Bent-Over Shrugs', 'Dumbbells', 'Traps', array['Forearms', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bent-over-shrugs-dumbbells'),
  (null, 'Bulgarian Split Squats', null, null, null, 'Bulgarian Split Squats', 'Barbell', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bulgarian-split-squats-barbell'),
  (null, 'Bulgarian Split Squats', null, null, null, 'Bulgarian Split Squats', 'Dumbbells', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:bulgarian-split-squats-dumbbells'),
  (null, 'Chin-Ups', null, null, null, 'Chin-Ups', 'Bodyweight', 'Lats', array['Upper Back', 'Forearms', 'Biceps', 'Rear Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:chin-ups-bodyweight'),
  (null, 'Concentration Curls', null, null, null, 'Concentration Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:concentration-curls-dumbbells'),
  (null, 'Concentration Hammer Curls', null, null, null, 'Concentration Hammer Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:concentration-hammer-curls-dumbbells'),
  (null, 'Concentration Twist Curls', null, null, null, 'Concentration Twist Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:concentration-twist-curls-dumbbells'),
  (null, 'Cross body curls', null, null, null, 'Cross body curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:cross-body-curls-dumbbells'),
  (null, 'Crunches', null, null, null, 'Crunches', 'Bodyweight', 'Abs', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:crunches-bodyweight'),
  (null, 'Crunches on Exercise Ball', null, null, null, 'Crunches on Exercise Ball', 'Bodyweight', 'Abs', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:crunches-on-exercise-ball-bodyweight'),
  (null, 'Curls', null, null, null, 'Curls', 'Barbell', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:curls-barbell'),
  (null, 'Curls', null, null, null, 'Curls', 'Cable', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:curls-cable'),
  (null, 'Curls', null, null, null, 'Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:curls-dumbbells'),
  (null, 'Curls (one arm)', null, null, null, 'Curls (one arm)', 'Cable', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:curls-one-arm-cable'),
  (null, 'Cycling on Stationary Bike', null, null, null, 'Cycling on Stationary Bike', 'Machine', 'Cardio', array['Quads'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:cycling-on-stationary-bike-machine'),
  (null, 'Deadlifts', null, null, null, 'Deadlifts', 'Barbell', 'Glutes', array['Hamstrings', 'Quads', 'Upper Back', 'Lats', 'Traps', 'Rear Delts', 'Forearms', 'Abductors', 'Adductors', 'Lower Back', 'Abs', 'Calves'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:deadlifts-barbell'),
  (null, 'Deadlifts', null, null, null, 'Deadlifts', 'Trap Bar', 'Glutes', array['Hamstrings', 'Quads', 'Upper Back', 'Lats', 'Traps', 'Rear Delts', 'Forearms', 'Abductors', 'Adductors', 'Lower Back', 'Abs', 'Calves'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:deadlifts-trap-bar'),
  (null, 'Decline Bench Press', null, null, null, 'Decline Bench Press', 'Barbell', 'Chest', array['Forearms', 'Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:decline-bench-press-barbell'),
  (null, 'Decline Bench Press', null, null, null, 'Decline Bench Press', 'Dumbbells', 'Chest', array['Forearms', 'Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:decline-bench-press-dumbbells'),
  (null, 'Decline Crunches', null, null, null, 'Decline Crunches', 'Bodyweight', 'Abs', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:decline-crunches-bodyweight'),
  (null, 'Decline Side Crunches', null, null, null, 'Decline Side Crunches', 'Bodyweight', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:decline-side-crunches-bodyweight'),
  (null, 'Decline Side Sit-Ups', null, null, null, 'Decline Side Sit-Ups', 'Bodyweight', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:decline-side-sit-ups-bodyweight'),
  (null, 'Decline Sit-Ups', null, null, null, 'Decline Sit-Ups', 'Bodyweight', 'Abs', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:decline-sit-ups-bodyweight'),
  (null, 'Deficit Deadlifts', null, null, null, 'Deficit Deadlifts', 'Trap Bar', 'Hamstrings', array['Hamstrings', 'Quads', 'Upper Back', 'Lats', 'Traps', 'Rear Delts', 'Forearms', 'Abductors', 'Adductors', 'Lower Back', 'Abs', 'Calves'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:deficit-deadlifts-trap-bar'),
  (null, 'Dips', null, null, null, 'Dips', 'Bodyweight', 'Triceps', array['Chest', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:dips-bodyweight'),
  (null, 'Drag Curls', null, null, null, 'Drag Curls', 'Barbell', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:drag-curls-barbell'),
  (null, 'Face Pulls with Rope', null, null, null, 'Face Pulls with Rope', 'Cable', 'Rear Delts', array['Upper Back', 'Traps', 'Side Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:face-pulls-with-rope-cable'),
  (null, 'Flys', null, null, null, 'Flys', 'Cable', 'Chest', array['Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:flys-cable'),
  (null, 'Flys', null, null, null, 'Flys', 'Dumbbells', 'Chest', array['Biceps', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:flys-dumbbells'),
  (null, 'Forward Lunges', null, null, null, 'Forward Lunges', 'Dumbbells', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:forward-lunges-dumbbells'),
  (null, 'Front Squats', null, null, null, 'Front Squats', 'Barbell', 'Quads', array['Glutes', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Upper Back', 'Traps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:front-squats-barbell'),
  (null, 'Goblet Squats', null, null, null, 'Goblet Squats', 'Dumbbells', 'Quads', array['Glutes', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Upper Back', 'Traps', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:goblet-squats-dumbbells'),
  (null, 'Good Mornings', null, null, null, 'Good Mornings', 'Barbell', 'Hamstrings', array['Glutes', 'Quads', 'Abductors', 'Adductors', 'Lower Back', 'Abs', 'Calves'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:good-mornings-barbell'),
  (null, 'Hammer Curls', null, null, null, 'Hammer Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:hammer-curls-dumbbells'),
  (null, 'Hammer Curls (Tri bar)', null, null, null, 'Hammer Curls (Tri bar)', 'EZ Curl Bar', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:hammer-curls-tri-bar-ez-curl-bar'),
  (null, 'Hanging Leg Raises', null, null, null, 'Hanging Leg Raises', 'Bodyweight', 'Abs', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:hanging-leg-raises-bodyweight'),
  (null, 'Hanging Leg Raises with Twist', null, null, null, 'Hanging Leg Raises with Twist', 'Bodyweight', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:hanging-leg-raises-with-twist-bodyweight'),
  (null, 'High Cable Flys', null, null, null, 'High Cable Flys', 'Cable', 'Chest', array['Biceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:high-cable-flys-cable'),
  (null, 'Hip Thrusts', null, null, null, 'Hip Thrusts', 'Barbell', 'Glutes', array['Hamstrings', 'Quads', 'Abductors', 'Adductors', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:hip-thrusts-barbell'),
  (null, 'Hyperextensions on Roman Chair', null, null, null, 'Hyperextensions on Roman Chair', 'Bodyweight', 'Hamstrings', array['Glutes', 'Abductors', 'Adductors', 'Lower Back'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:hyperextensions-on-roman-chair-bodyweight'),
  (null, 'Incline Bench Hex Press', null, null, null, 'Incline Bench Hex Press', 'Dumbbells', 'Upper Chest', array['Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-bench-hex-press-dumbbells'),
  (null, 'Incline Bench Press', null, null, null, 'Incline Bench Press', 'Barbell', 'Chest', array['Upper Chest', 'Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-bench-press-barbell'),
  (null, 'Incline Bench Press', null, null, null, 'Incline Bench Press', 'Dumbbells', 'Chest', array['Upper Chest', 'Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-bench-press-dumbbells'),
  (null, 'Incline Bench Press 20°', null, null, null, 'Incline Bench Press 20°', 'Dumbbells', 'Chest', array['Upper Chest', 'Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-bench-press-20-dumbbells'),
  (null, 'Incline Bench Press 60°', null, null, null, 'Incline Bench Press 60°', 'Dumbbells', 'Chest', array['Upper Chest', 'Triceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-bench-press-60-dumbbells'),
  (null, 'Incline Bench Press with Close Grip', null, null, null, 'Incline Bench Press with Close Grip', 'Barbell', 'Triceps', array['Chest', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-bench-press-with-close-grip-barbell'),
  (null, 'Incline Curls', null, null, null, 'Incline Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-curls-dumbbells'),
  (null, 'Incline Flys', null, null, null, 'Incline Flys', 'Dumbbells', 'Chest', array['Upper Chest', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-flys-dumbbells'),
  (null, 'Incline Flys 20-deg', null, null, null, 'Incline Flys 20-deg', 'Dumbbells', 'Chest', array['Upper Chest', 'Biceps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-flys-20-deg-dumbbells'),
  (null, 'Incline Hammer Curls', null, null, null, 'Incline Hammer Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-hammer-curls-dumbbells'),
  (null, 'Incline Lateral Raises', null, null, null, 'Incline Lateral Raises', 'Dumbbells', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-lateral-raises-dumbbells'),
  (null, 'Incline Reverse Flys', null, null, null, 'Incline Reverse Flys', 'Dumbbells', 'Rear Delts', array['Traps', 'Side Delts', 'Upper Back', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-reverse-flys-dumbbells'),
  (null, 'Incline Rows', null, null, null, 'Incline Rows', 'Dumbbells', 'Upper Back', array['Lats', 'Traps', 'Biceps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-rows-dumbbells'),
  (null, 'Incline Shrugs', null, null, null, 'Incline Shrugs', 'Dumbbells', 'Traps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-shrugs-dumbbells'),
  (null, 'Incline Skull Crushers', null, null, null, 'Incline Skull Crushers', 'Dumbbells', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-skull-crushers-dumbbells'),
  (null, 'Incline Skull Crushers', null, null, null, 'Incline Skull Crushers', 'EZ Curl Bar', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-skull-crushers-ez-curl-bar'),
  (null, 'Incline Twist Curls', null, null, null, 'Incline Twist Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:incline-twist-curls-dumbbells'),
  (null, 'JM Press', null, null, null, 'JM Press', 'Barbell', 'Triceps', array['Chest', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:jm-press-barbell'),
  (null, 'JM Press', null, null, null, 'JM Press', 'EZ Curl Bar', 'Triceps', array['Chest', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:jm-press-ez-curl-bar'),
  (null, 'Kneeling Crunches', null, null, null, 'Kneeling Crunches', 'Cable', 'Abs', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:kneeling-crunches-cable'),
  (null, 'Kneeling Side Crunches', null, null, null, 'Kneeling Side Crunches', 'Cable', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:kneeling-side-crunches-cable'),
  (null, 'Landmine Hack Squats', null, null, null, 'Landmine Hack Squats', 'Landmine', 'Quads', array['Glutes', 'Hamstrings', 'Abductors', 'Adductors', 'Calves'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:landmine-hack-squats-bodyweight'),
  (null, 'Lat Pulldowns with Close Neutral Grip', null, null, null, 'Lat Pulldowns with Close Neutral Grip', 'Cable', 'Lats', array['Upper Back', 'Rear Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lat-pulldowns-with-close-neutral-grip-cable'),
  (null, 'Lat Pulldowns with Close Overhand Grip', null, null, null, 'Lat Pulldowns with Close Overhand Grip', 'Cable', 'Lats', array['Upper Back', 'Rear Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lat-pulldowns-with-close-overhand-grip-cable'),
  (null, 'Lat Pulldowns with Reverse Grip', null, null, null, 'Lat Pulldowns with Reverse Grip', 'Cable', 'Lats', array['Upper Back', 'Rear Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lat-pulldowns-with-reverse-grip-cable'),
  (null, 'Lat Pulldowns with Wide Neutral Grip', null, null, null, 'Lat Pulldowns with Wide Neutral Grip', 'Cable', 'Lats', array['Upper Back', 'Rear Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lat-pulldowns-with-wide-neutral-grip-cable'),
  (null, 'Lat Pulldowns with Wide Overhand Grip', null, null, null, 'Lat Pulldowns with Wide Overhand Grip', 'Cable', 'Lats', array['Upper Back', 'Rear Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lat-pulldowns-with-wide-overhand-grip-cable'),
  (null, 'Lateral Raises', null, null, null, 'Lateral Raises', 'Dumbbells', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lateral-raises-dumbbells'),
  (null, 'Lean Away Lateral Raises', null, null, null, 'Lean Away Lateral Raises', 'Cable', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lean-away-lateral-raises-cable'),
  (null, 'Lean Away Lateral Raises', null, null, null, 'Lean Away Lateral Raises', 'Dumbbells', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lean-away-lateral-raises-dumbbells'),
  (null, 'Leg Extensions', null, null, null, 'Leg Extensions', 'Machine', 'Quads', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:leg-extensions-machine'),
  (null, 'Lying Leg Curls', null, null, null, 'Lying Leg Curls', 'Resistance Band', 'Hamstrings', array['Abductors', 'Adductors', 'Calves'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:lying-leg-curls-resistance-band'),
  (null, 'One-Arm Lateral Raises at Hip Height', null, null, null, 'One-Arm Lateral Raises at Hip Height', 'Cable', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:one-arm-lateral-raises-at-hip-height-cable'),
  (null, 'One-Arm Rows', null, null, null, 'One-Arm Rows', 'Dumbbells', 'Upper Back', array['Lats', 'Biceps', 'Traps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:one-arm-rows-dumbbells'),
  (null, 'One-Arm Rows with Reverse Grip', null, null, null, 'One-Arm Rows with Reverse Grip', 'Dumbbells', 'Upper Back', array['Lats', 'Biceps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:one-arm-rows-with-reverse-grip-dumbbells'),
  (null, 'One-Arm Rows with Wide Grip', null, null, null, 'One-Arm Rows with Wide Grip', 'Dumbbells', 'Upper Back', array['Lats', 'Biceps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:one-arm-rows-with-wide-grip-dumbbells'),
  (null, 'Overhead Shrugs', null, null, null, 'Overhead Shrugs', 'Barbell', 'Traps', array['Forearms', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:overhead-shrugs-barbell'),
  (null, 'Overhead Triceps Extensions', null, null, null, 'Overhead Triceps Extensions', 'Cable', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:overhead-triceps-extensions-cable'),
  (null, 'Overhead Triceps Extensions', null, null, null, 'Overhead Triceps Extensions', 'Dumbbells', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:overhead-triceps-extensions-dumbbells'),
  (null, 'Overhead Triceps Extensions', null, null, null, 'Overhead Triceps Extensions', 'EZ Curl Bar', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:overhead-triceps-extensions-ez-curl-bar'),
  (null, 'Preacher Curls', null, null, null, 'Preacher Curls', 'EZ Curl Bar', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:preacher-curls-ez-curl-bar'),
  (null, 'Preacher Hammer Curls', null, null, null, 'Preacher Hammer Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:preacher-hammer-curls-dumbbells'),
  (null, 'Preacher Twist Curls', null, null, null, 'Preacher Twist Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:preacher-twist-curls-dumbbells'),
  (null, 'Pull-Ups with Close Neutral Grip', null, null, null, 'Pull-Ups with Close Neutral Grip', 'Bodyweight', 'Lats', array['Upper Back', 'Biceps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:pull-ups-with-close-neutral-grip-bodyweight'),
  (null, 'Pull-Ups with Close Overhand Grip', null, null, null, 'Pull-Ups with Close Overhand Grip', 'Bodyweight', 'Lats', array['Upper Back', 'Biceps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:pull-ups-with-close-overhand-grip-bodyweight'),
  (null, 'Pull-Ups with Wide Overhand Grip', null, null, null, 'Pull-Ups with Wide Overhand Grip', 'Bodyweight', 'Lats', array['Upper Back', 'Biceps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:pull-ups-with-wide-overhand-grip-bodyweight'),
  (null, 'Pullovers', null, null, null, 'Pullovers', 'Cable', 'Lats', array['Chest', 'Triceps', 'Upper Back', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:pullovers-cable'),
  (null, 'Pullovers on Bench', null, null, null, 'Pullovers on Bench', 'Dumbbells', 'Lats', array['Chest', 'Triceps', 'Upper Back', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:pullovers-on-bench-dumbbells'),
  (null, 'Pullovers on Bench', null, null, null, 'Pullovers on Bench', 'EZ Curl Bar', 'Lats', array['Chest', 'Triceps', 'Upper Back', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:pullovers-on-bench-ez-curl-bar'),
  (null, 'Pullovers with Rope', null, null, null, 'Pullovers with Rope', 'Cable', 'Lats', array['Chest', 'Triceps', 'Upper Back', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:pullovers-with-rope-cable'),
  (null, 'Push-Ups with Close Grip', null, null, null, 'Push-Ups with Close Grip', 'Bodyweight', 'Triceps', array['Chest', 'Front Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:push-ups-with-close-grip-bodyweight'),
  (null, 'Reverse Curls', null, null, null, 'Reverse Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:reverse-curls-dumbbells'),
  (null, 'Reverse Curls', null, null, null, 'Reverse Curls', 'EZ Curl Bar', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:reverse-curls-ez-curl-bar'),
  (null, 'Reverse Flys', null, null, null, 'Reverse Flys', 'Cable', 'Rear Delts', array['Traps', 'Side Delts', 'Upper Back', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:reverse-flys-cable'),
  (null, 'Reverse Lunges', null, null, null, 'Reverse Lunges', 'Dumbbells', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:reverse-lunges-dumbbells'),
  (null, 'Reverse Spider Curls', null, null, null, 'Reverse Spider Curls', 'EZ Curl Bar', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:reverse-spider-curls-ez-curl-bar'),
  (null, 'Romanian Deadlifts', null, null, null, 'Romanian Deadlifts', 'Barbell', 'Hamstrings', array['Glutes', 'Quads', 'Upper Back', 'Lats', 'Traps', 'Rear Delts', 'Forearms', 'Abductors', 'Adductors', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:romanian-deadlifts-barbell'),
  (null, 'Romanian Deadlifts', null, null, null, 'Romanian Deadlifts', 'Dumbbells', 'Hamstrings', array['Glutes', 'Quads', 'Upper Back', 'Lats', 'Traps', 'Rear Delts', 'Forearms', 'Abductors', 'Adductors', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:romanian-deadlifts-dumbbells'),
  (null, 'Romanian Deadlifts', null, null, null, 'Romanian Deadlifts', 'Trap Bar', 'Hamstrings', array['Glutes', 'Quads', 'Upper Back', 'Lats', 'Traps', 'Rear Delts', 'Forearms', 'Abductors', 'Adductors', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:romanian-deadlifts-trap-bar'),
  (null, 'Rows with Close Grip', null, null, null, 'Rows with Close Grip', 'Cable', 'Upper Back', array['Lats', 'Traps', 'Biceps', 'Rear Delts', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:rows-with-close-grip-cable'),
  (null, 'Rows with Reverse Grip', null, null, null, 'Rows with Reverse Grip', 'Cable', 'Upper Back', array['Lats', 'Traps', 'Biceps', 'Rear Delts', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:rows-with-reverse-grip-cable'),
  (null, 'Rows with Wide Grip', null, null, null, 'Rows with Wide Grip', 'Cable', 'Upper Back', array['Lats', 'Traps', 'Biceps', 'Rear Delts', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:rows-with-wide-grip-cable'),
  (null, 'Rows with Wide Neutral Grip', null, null, null, 'Rows with Wide Neutral Grip', 'Cable', 'Upper Back', array['Lats', 'Traps', 'Biceps', 'Rear Delts', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:rows-with-wide-neutral-grip-cable'),
  (null, 'Russian Twists', null, null, null, 'Russian Twists', 'Bodyweight', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:russian-twists-bodyweight'),
  (null, 'Seated Bent-Over Lateral Raises', null, null, null, 'Seated Bent-Over Lateral Raises', 'Dumbbells', 'Rear Delts', array['Traps', 'Side Delts', 'Upper Back', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-bent-over-lateral-raises-dumbbells'),
  (null, 'Seated Calf Raises', null, null, null, 'Seated Calf Raises', 'Bodyweight', 'Calves', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-calf-raises-bodyweight'),
  (null, 'Seated Calf Raises (BB)', null, null, null, 'Seated Calf Raises (BB)', 'Barbell', 'Calves', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-calf-raises-bb-barbell'),
  (null, 'Seated Lateral Raises', null, null, null, 'Seated Lateral Raises', 'Dumbbells', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-lateral-raises-dumbbells'),
  (null, 'Seated Leg Curls', null, null, null, 'Seated Leg Curls', 'Machine', 'Hamstrings', array['Abductors', 'Adductors'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-leg-curls-machine'),
  (null, 'Seated Shoulder Press', null, null, null, 'Seated Shoulder Press', 'Barbell', 'Front Delts', array['Side Delts', 'Traps', 'Triceps', 'Chest', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-shoulder-press-barbell'),
  (null, 'Seated Shoulder Press', null, null, null, 'Seated Shoulder Press', 'Dumbbells', 'Shoulders', array['Side Delts', 'Traps', 'Triceps', 'Chest', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-shoulder-press-dumbbells'),
  (null, 'Seated Shoulder Press with Close Grip', null, null, null, 'Seated Shoulder Press with Close Grip', 'Dumbbells', 'Shoulders', array['Side Delts', 'Traps', 'Triceps', 'Chest', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:seated-shoulder-press-with-close-grip-dumbbells'),
  (null, 'Shrugs', null, null, null, 'Shrugs', 'Barbell', 'Traps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:shrugs-barbell'),
  (null, 'Shrugs', null, null, null, 'Shrugs', 'Dumbbells', 'Traps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:shrugs-dumbbells'),
  (null, 'Shrugs', null, null, null, 'Shrugs', 'Trap Bar', 'Traps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:shrugs-trap-bar'),
  (null, 'Side Bends', null, null, null, 'Side Bends', 'Dumbbells', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:side-bends-dumbbells'),
  (null, 'Side Crunches', null, null, null, 'Side Crunches', 'Bodyweight', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:side-crunches-bodyweight'),
  (null, 'Side Sit-Ups', null, null, null, 'Side Sit-Ups', 'Bodyweight', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:side-sit-ups-bodyweight'),
  (null, 'Sit-Ups', null, null, null, 'Sit-Ups', 'Bodyweight', 'Abs', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:sit-ups-bodyweight'),
  (null, 'Skull Crushers', null, null, null, 'Skull Crushers', 'Dumbbells', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:skull-crushers-dumbbells'),
  (null, 'Skull Crushers', null, null, null, 'Skull Crushers', 'EZ Curl Bar', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:skull-crushers-ez-curl-bar'),
  (null, 'Skull Crushers with Rope', null, null, null, 'Skull Crushers with Rope', 'Cable', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:skull-crushers-with-rope-cable'),
  (null, 'Spider Curls', null, null, null, 'Spider Curls', 'Barbell', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:spider-curls-barbell'),
  (null, 'Split Squats', null, null, null, 'Split Squats', 'Dumbbells', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:split-squats-dumbbells'),
  (null, 'Squats', null, null, null, 'Squats', 'Barbell', 'Quads', array['Glutes', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:squats-barbell'),
  (null, 'Squats (Belt)', null, null, null, 'Squats (Belt)', 'Bodyweight', 'Quads', array['Glutes', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:squats-belt-bodyweight'),
  (null, 'Standing Calf Raises', null, null, null, 'Standing Calf Raises', 'Bodyweight', 'Calves', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:standing-calf-raises-bodyweight'),
  (null, 'Standing Calf Raises', null, null, null, 'Standing Calf Raises', 'Smith Machine', 'Calves', '{}', true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:standing-calf-raises-smith-machine'),
  (null, 'Standing Leg Curls', null, null, null, 'Standing Leg Curls', 'Cable', 'Hamstrings', array['Abductors', 'Adductors'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:standing-leg-curls-cable'),
  (null, 'Standing Russian Twists', null, null, null, 'Standing Russian Twists', 'Cable', 'Abs', array['Obliques'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:standing-russian-twists-cable'),
  (null, 'Standing Shoulder Press', null, null, null, 'Standing Shoulder Press', 'Barbell', 'Front Delts', array['Side Delts', 'Traps', 'Triceps', 'Chest', 'Forearms', 'Lower Back'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:standing-shoulder-press-barbell'),
  (null, 'Standing Shoulder Press with Close Grip', null, null, null, 'Standing Shoulder Press with Close Grip', 'Dumbbells', 'Shoulders', array['Side Delts', 'Traps', 'Triceps', 'Chest', 'Forearms', 'Lower Back'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:standing-shoulder-press-with-close-grip-dumbbells'),
  (null, 'Step-Ups', null, null, null, 'Step-Ups', 'Dumbbells', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:step-ups-dumbbells'),
  (null, 'Sumo Deadlifts', null, null, null, 'Sumo Deadlifts', 'Barbell', 'Glutes', array['Hamstrings', 'Quads', 'Upper Back', 'Lats', 'Traps', 'Rear Delts', 'Forearms', 'Abductors', 'Adductors', 'Lower Back', 'Abs', 'Calves'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:sumo-deadlifts-barbell'),
  (null, 'T-Bar Reverse Lunges', null, null, null, 'T-Bar Reverse Lunges', 'Landmine', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:t-bar-reverse-lunges-barbell'),
  (null, 'T-Bar Rows with Wide Grip', null, null, null, 'T-Bar Rows with Wide Grip', 'Landmine', 'Upper Back', array['Lats', 'Traps', 'Rear Delts', 'Biceps', 'Forearms', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:t-bar-rows-with-wide-grip-barbell'),
  (null, 'Triceps Kickbacks', null, null, null, 'Triceps Kickbacks', 'Cable', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:triceps-kickbacks-cable'),
  (null, 'Triceps Kickbacks', null, null, null, 'Triceps Kickbacks', 'Dumbbells', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:triceps-kickbacks-dumbbells'),
  (null, 'Triceps Pushdowns', null, null, null, 'Triceps Pushdowns', 'Cable', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:triceps-pushdowns-cable'),
  (null, 'Triceps Pushdowns (Vbar)', null, null, null, 'Triceps Pushdowns (Vbar)', 'Cable', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:triceps-pushdowns-vbar-cable'),
  (null, 'Triceps Pushdowns with Rope', null, null, null, 'Triceps Pushdowns with Rope', 'Cable', 'Triceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:triceps-pushdowns-with-rope-cable'),
  (null, 'Twist Curls', null, null, null, 'Twist Curls', 'Dumbbells', 'Biceps', array['Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:twist-curls-dumbbells'),
  (null, 'Upright Rows', null, null, null, 'Upright Rows', 'Dumbbells', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:upright-rows-dumbbells'),
  (null, 'Upright Rows', null, null, null, 'Upright Rows', 'EZ Curl Bar', 'Shoulders', array['Traps', 'Front Delts', 'Rear Delts', 'Biceps', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:upright-rows-ez-curl-bar'),
  (null, 'Walking Lunges', null, null, null, 'Walking Lunges', 'Dumbbells', 'Glutes', array['Quads', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:walking-lunges-dumbbells'),
  (null, 'Y Raises', null, null, null, 'Y Raises', 'Cable', 'Side Delts', array['Traps', 'Front Delts', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:y-raises-cable'),
  (null, 'Zercher Squats', null, null, null, 'Zercher Squats', 'Barbell', 'Quads', array['Glutes', 'Hamstrings', 'Abductors', 'Adductors', 'Calves', 'Lower Back', 'Abs', 'Upper Back', 'Traps', 'Front Delts'], true, 'curated_exercise_library_v1', 'history-csv-2026-06-07:zercher-squats-barbell'),
  (null, 'Push-Ups', null, null, null, 'Push-Ups', 'Bodyweight', 'Chest', array['Front Delts', 'Triceps', 'Forearms'], true, 'curated_exercise_library_v1', 'manual-2026-06-09:push-ups-bodyweight'),
  (null, 'Pull-Ups with Wide Neutral Grip', null, null, null, 'Pull-Ups with Wide Neutral Grip', 'Bodyweight', 'Lats', array['Upper Back', 'Biceps', 'Rear Delts', 'Forearms'], true, 'curated_exercise_library_v1', 'manual-2026-06-09:pull-ups-with-wide-neutral-grip-bodyweight'),
  (null, 'T-Bar Rows with Narrow Grip', null, null, null, 'T-Bar Rows with Narrow Grip', 'Landmine', 'Upper Back', array['Lats', 'Traps', 'Rear Delts', 'Biceps', 'Forearms', 'Lower Back', 'Abs'], true, 'curated_exercise_library_v1', 'manual-2026-06-09:t-bar-rows-with-narrow-grip-landmine'),
  (null, 'Front Raises', null, null, null, 'Front Raises', 'Barbell', 'Front Delts', array['Side Delts', 'Traps', 'Forearms'], true, 'curated_exercise_library_v1', 'manual-2026-06-09:front-raises-barbell'),
  (null, 'Front Raises', null, null, null, 'Front Raises', 'Dumbbells', 'Front Delts', array['Side Delts', 'Traps', 'Forearms'], true, 'curated_exercise_library_v1', 'manual-2026-06-09:front-raises-dumbbells'),
  (null, 'Front Raises', null, null, null, 'Front Raises', 'EZ Curl Bar', 'Front Delts', array['Side Delts', 'Traps', 'Forearms'], true, 'curated_exercise_library_v1', 'manual-2026-06-09:front-raises-ez-curl-bar')
on conflict (source, source_key) where user_id is null
do update set
  name = excluded.name,
  description = excluded.description,
  image_url = excluded.image_url,
  image_storage_path = excluded.image_storage_path,
  image_alt = excluded.image_alt,
  equipment = excluded.equipment,
  primary_muscle = excluded.primary_muscle,
  secondary_muscles = excluded.secondary_muscles,
  is_builtin = true,
  updated_at = now(),
  deleted_at = null;

commit;
